import { beforeEach, describe, expect, it, vi } from 'vitest';
import { render, screen, within } from '@testing-library/react';
import type {
  AiStatusResponse,
  CategoryBreakdownResponse,
  EventInsightsResponse,
} from '@eventq/contracts';
import { ApiError } from '@/lib/api-client';
import { EventInsights } from './event-insights';

/**
 * Event Insights.
 *
 * The rule these tests protect is the one the page exists for: a measured
 * fact and an AI interpretation are never shown as the same kind of thing.
 * Facts live in one section that says nothing in it came from AI; anything
 * a model produced lives in a separate section under an "AI-generated" label,
 * with the model and the coverage beside it — and a failure on the AI side
 * never takes the facts down.
 */
const {
  getEventInsights,
  getEvent,
  getAiStatus,
  getCategoryBreakdown,
  listTopics,
  getLatestSummary,
  replace,
} = vi.hoisted(() => ({
  getEventInsights: vi.fn(),
  getEvent: vi.fn(),
  getAiStatus: vi.fn(),
  getCategoryBreakdown: vi.fn(),
  listTopics: vi.fn(),
  getLatestSummary: vi.fn(),
  replace: vi.fn(),
}));

vi.mock('@/lib/api-client/organizer', () => ({
  getEventInsights,
  getEvent,
  getAiStatus,
  getCategoryBreakdown,
  listTopics,
  getLatestSummary,
}));

vi.mock('next/navigation', () => ({
  useRouter: () => ({ replace, push: vi.fn(), refresh: vi.fn() }),
}));

const EVENT_ID = '01930000-0000-7000-8000-0000000000e1';
const id = (n: number) => `01930000-0000-7000-8000-${String(n).padStart(12, '0')}`;

function insights(overrides: Partial<EventInsightsResponse> = {}): EventInsightsResponse {
  return {
    eventId: EVENT_ID,
    computedAt: '2026-09-23T12:00:00.000Z',
    questions: {
      submitted: 87,
      byStatus: { PENDING: 3, APPROVED: 12, ANSWERED: 60, REJECTED: 5, SPAM: 2, ARCHIVED: 5 },
      mergedAsDuplicate: 5,
      unanswered: 12,
      answerRate: 60 / 72,
    },
    engagement: { votes: 240, askers: 41, voters: 70, participants: 78 },
    highlights: {
      mostUpvoted: {
        id: id(1),
        body: 'How can small businesses use AI?',
        status: 'ANSWERED',
        upvoteCount: 31,
        askedByCount: 4,
      },
      mostAsked: null,
      unanswered: [
        {
          id: id(2),
          body: 'What does a first AI pilot cost?',
          status: 'APPROVED',
          upvoteCount: 9,
          askedByCount: 1,
        },
      ],
    },
    timeline: {
      bucketMinutes: 10,
      buckets: [
        { start: '2026-09-23T10:00:00.000Z', count: 12 },
        { start: '2026-09-23T10:10:00.000Z', count: 0 },
        { start: '2026-09-23T10:20:00.000Z', count: 30 },
      ],
    },
    duplicates: { groups: 3, awaitingReview: 1, largest: [] },
    moderation: { mode: 'PRE', moderatorApproved: 72, medianWaitSeconds: 95 },
    frequentTerms: {
      analysed: 75,
      truncated: false,
      terms: [{ term: 'marketing', questions: 18, share: 0.24 }],
    },
    ...overrides,
  };
}

function aiStatus(overrides: Partial<AiStatusResponse> = {}): AiStatusResponse {
  return {
    availableOnServer: false,
    enabledForEvent: false,
    eventSpendMicros: 0,
    eventBudgetMicros: 2_000_000,
    monthlySpendMicros: 0,
    monthlyBudgetMicros: 50_000_000,
    callsByFeature: {
      CLASSIFICATION: 0,
      DEDUPLICATION: 0,
      CLUSTERING: 0,
      ANSWER_SUGGESTION: 0,
      SUMMARIZATION: 0,
    },
    models: {
      CLASSIFICATION: 'claude-haiku-4-5',
      DEDUPLICATION: 'claude-haiku-4-5',
      CLUSTERING: 'claude-sonnet-5',
      ANSWER_SUGGESTION: 'claude-sonnet-5',
      SUMMARIZATION: 'claude-sonnet-5',
    },
    ...overrides,
  };
}

const NO_CATEGORIES: CategoryBreakdownResponse = {
  categories: [],
  categorized: 0,
  uncategorized: 75,
  modelIds: [],
  lastCategorizedAt: null,
};

beforeEach(() => {
  vi.clearAllMocks();
  getEventInsights.mockResolvedValue(insights());
  getEvent.mockResolvedValue({ id: EVENT_ID, title: 'AI in Business Breakfast' });
  getAiStatus.mockResolvedValue(aiStatus());
  getCategoryBreakdown.mockResolvedValue(NO_CATEGORIES);
  listTopics.mockResolvedValue([]);
  getLatestSummary.mockResolvedValue({ summary: null });
});

async function sections() {
  const facts = await screen.findByRole('region', { name: 'Measured facts' });
  const ai = screen.getByRole('region', { name: /AI interpretation/ });
  return { facts, ai };
}

describe('EventInsights', () => {
  it('shows the measured numbers in a section that disclaims AI', async () => {
    render(<EventInsights eventId={EVENT_ID} />);
    const { facts } = await sections();

    expect(within(facts).getByText(/nothing in this section was generated by ai/i)).toBeVisible();
    expect(within(facts).getByText('87')).toBeInTheDocument();
    expect(within(facts).getByText('83%')).toBeInTheDocument();
    expect(within(facts).getByText('How can small businesses use AI?')).toBeInTheDocument();
    expect(within(facts).getByText('What does a first AI pilot cost?')).toBeInTheDocument();
    expect(within(facts).getByText('2 min')).toBeInTheDocument();
    // The facts section never wears the AI label.
    expect(within(facts).queryByText('AI-generated')).not.toBeInTheDocument();
  });

  it('says the word counts are counts, not meaning', async () => {
    render(<EventInsights eventId={EVENT_ID} />);
    const { facts } = await sections();

    expect(within(facts).getByText('marketing')).toBeInTheDocument();
    expect(within(facts).getByText(/counts words, not meaning/i)).toBeInTheDocument();
  });

  it('gives every timeline bar an accessible count, and a table', async () => {
    render(<EventInsights eventId={EVENT_ID} />);
    const { facts } = await sections();

    const bars = within(facts).getByRole('list', { name: /questions submitted per interval/i });
    expect(within(bars).getAllByRole('listitem')).toHaveLength(3);
    expect(within(bars).getByLabelText(/30 questions/)).toBeInTheDocument();
    expect(within(facts).getByRole('table')).toBeInTheDocument();
  });

  it('labels the AI section and says plainly that it is interpretation', async () => {
    render(<EventInsights eventId={EVENT_ID} />);
    const { ai } = await sections();

    expect(within(ai).getByText('AI-generated')).toBeInTheDocument();
    expect(within(ai).getByText(/interpretations, not measurements/i)).toBeInTheDocument();
  });

  it('says nothing was generated when AI never ran — rather than showing an empty chart', async () => {
    render(<EventInsights eventId={EVENT_ID} />);
    const { ai } = await sections();

    expect(within(ai).getByText(/nothing has been generated for this event/i)).toBeInTheDocument();
    expect(within(ai).getByText(/not enabled on this server/i)).toBeInTheDocument();
  });

  it('shows stored AI results with their model, date and coverage', async () => {
    getCategoryBreakdown.mockResolvedValue({
      categories: [
        { category: 'AI', questions: 12 },
        { category: 'Marketing', questions: 8 },
      ],
      categorized: 20,
      uncategorized: 55,
      modelIds: ['claude-haiku-4-5'],
      lastCategorizedAt: '2026-09-23T11:00:00.000Z',
    });
    listTopics.mockResolvedValue([
      {
        id: id(9),
        label: 'Getting started with AI',
        summary: null,
        questionCount: 30,
        questionIds: [],
        generatedAt: '2026-09-23T11:05:00.000Z',
      },
    ]);
    getLatestSummary.mockResolvedValue({
      summary: {
        id: id(10),
        kind: 'LIVE',
        headline: 'The room wants a practical first step with AI.',
        themes: [],
        notableQuestions: [],
        suggestedFollowUps: ['Share a one-page AI pilot checklist.'],
        questionCount: 40,
        modelId: 'claude-sonnet-5',
        generatedAt: '2026-09-23T11:10:00.000Z',
        usage: null,
      },
    });

    render(<EventInsights eventId={EVENT_ID} />);
    const { facts, ai } = await sections();

    // Coverage: a breakdown of 20 questions must not pass for all 75.
    expect(within(ai).getByText(/placed 20 of 75 current questions/i)).toBeInTheDocument();
    expect(within(ai).getByText(/claude-haiku-4-5/)).toBeInTheDocument();
    expect(within(ai).getByText('Getting started with AI')).toBeInTheDocument();
    expect(within(ai).getByText(/35 newer questions are not in it/i)).toBeInTheDocument();
    expect(
      within(ai).getByText('The room wants a practical first step with AI.'),
    ).toBeInTheDocument();

    // And none of it leaks into the facts.
    expect(within(facts).queryByText('Getting started with AI')).not.toBeInTheDocument();
    expect(
      within(facts).queryByText('The room wants a practical first step with AI.'),
    ).not.toBeInTheDocument();
  });

  it('keeps the facts on screen when the AI side fails to load', async () => {
    getAiStatus.mockRejectedValue(new Error('network'));

    render(<EventInsights eventId={EVENT_ID} />);
    const { facts, ai } = await sections();

    expect(within(facts).getByText('87')).toBeInTheDocument();
    expect(within(ai).getByText(/could not load the ai interpretation/i)).toBeInTheDocument();
  });

  it('sends an expired session to sign-in, back to this page', async () => {
    getEventInsights.mockRejectedValue(
      new ApiError(
        {
          type: 'about:blank',
          title: 'Unauthorized',
          status: 401,
          code: 'UNAUTHENTICATED',
          traceId: 'trace-1',
        },
        401,
      ),
    );

    render(<EventInsights eventId={EVENT_ID} />);

    await vi.waitFor(() =>
      expect(replace).toHaveBeenCalledWith(
        `/sign-in?next=${encodeURIComponent(`/dashboard/events/${EVENT_ID}/insights`)}`,
      ),
    );
  });
});
